### ISSUE TITLE
0.15 可能須要緊急修正

### ISSUE THREAD

**Issue by KenLuoTW** [EasyIME/forum#10]
因為我發現新酷音模組換頁時,候選清單會消失掉,已經修正於 https://github.com/EasyIME/PIME/commit/b47ee6bc74917e20a2b984fb498ac7cb8565d19f .
中州韻有測試過,並沒有這個問題。

另外我發現用 0.15 正式版安裝,在 Win7 下依然有問題。
我自己包的 0.15 test 05,則正常。

**Comment by PCMan** [comment]
@KenLuoTW 你包的 0.15 有特別做什麼不同的處理嗎?
我全部重新編譯最新的 git 之後包的... 囧rz

**Comment by KenLuoTW** [comment]
@PCMan 我沒有特別處理喔~

**Comment by PCMan** [comment]
果然 win7 下有問題，可是在win7 重新編譯就正常了，不知道到底發生什麼事情....

**Comment by KenLuoTW** [comment]
我是在 win10 下編譯的,所以在 win10 下應該也可正常編譯,不太清楚是什麼問題。

已測試過 0.15.1,在 win7 下安裝都正常了,感謝~~

另外因為都在 win10 環境上測試,剛測試 win7時,
我有發現 cin 系列輸入法在 win7 語言列上有一些問題,
會導致程序卡死,算是一個明顯且嚴重的問題,
是否介意我在修復後,自行發行緊急修正版本。

**Comment by PCMan** [comment]
@KenLuoTW 沒問題，你修好測試好沒問題，就自己 release 吧! :)
辛苦了！感謝這麼多貢獻

**Comment by HPEACE** [comment]
不曉得 0.15.1版本的問題是否打在這....
之前没發生命令模式下没辦法打字，現在已經可以了所以測了一下發現，在命令模式內的輸入法狀態好像不會正常顯示，一直是秀「全」

**Comment by osfans** [comment]
@HPEACE 確實如此，狀態不對。另外zh-TW的系統，無法在命令模式內使用zh-CN的輸入法。這是微軟的問題。

**Comment by KenLuoTW** [comment]
@PCMan 人不在家中,還在值班中,後天我下班後弄一下,就更新。
@osfans Windows 的 console 一直都很爛,字碼頁切到 UTF-8 會連微軟內建的輸入法都不能用。
不過可以參考一下 https://conemu.github.io/
