### ISSUE TITLE
傳統注音聯想字詞能否協助修改成按Shift + 數字鍵選擇

### ISSUE THREAD

**Issue by Cheniyuan** [EasyIME/forum#14]
開發者您好

我還有一群朋友，是早期用傳統注音的使用者
很謝謝PIME還有所照顧到我們這群在Windows 10下的傳統使用者。
目前用起來都還蠻就手，唯獨聯想字詞這個功能，
目前是直接按數字選聯想詞，但我們習慣問題，
現階段的設定，如果開啟聯想字詞功能，跟我們習慣不同之外，
還容易會出現不市我們要輸入的文字，希望下ㄧ版的傳統注音，
能把聯想字詞的功能，改成原本Shift鍵加上數字鍵的選擇方式。

謝謝你們的付出

**Comment by KenLuoTW** [comment]
最近正在撰寫公司要用的工具程式,暫時沒有時間修改,
以後比較有空時會將此建議納入更新內容。

**Comment by KenLuoTW** [comment]
已修正此問題於 https://github.com/EasyIME/PIME/commit/1386201197e8936d5caa6f707c70135bcc363de7

**Comment by Cheniyuan** [comment]
謝謝，現在就來下載試試

**Comment by KenLuoTW** [comment]
目前未有測試版喔,改在原碼裡。
今天沒空弄測試版了,明天我會弄出來。

**Comment by Cheniyuan** [comment]
謝謝你
我有看到源碼你有修正
那就等你發佈，我再叫我朋友一起載來用

**Comment by Cheniyuan** [comment]
請問到時您發怖，是會發佈在0.16的版本中嗎?
還是0.15會再出ㄧ版?
謝謝

**Comment by KenLuoTW** [comment]
最近忙, 不過現在 0.16 正式版中已包含此修正。

**Comment by Cheniyuan** [comment]
我已經下載使用0.16版了
謝謝你的付出，覺得更好用!
會去各大論壇幫你們推廣
加油
