### ISSUE TITLE
關於：升級到0.14版之後，大新倉頡自定義檔使用問題

### ISSUE THREAD

**Issue by sirius95** [EasyIME/forum#2]
朋友們好：

先前在知用0.13版時，經朋友指點，得知如何自定義輸出文字、符號或數字等...當時做法即是在此路徑

C:\Program Files (x86)\PIME\server\input_methods\newcj 之中的【newcj.cin】檔，打開後，在裡面填

入欲定義的按鍵，例如我定義的幾個按鍵來輸出箭頭符號：
rar →
lar ←
當時我定義完之後，也沒什麼改變，還是無法出現我所要的符號，於是也在朋友指點之下，得知要在

（設定輸入法模組）裡，將（輸入法碼表）先選為其它非自由大新輸入法，按完確定之後，再重新在

（輸入法碼表）裡，選回原本的自由大新輸入法，果真這麼做之後，自己所定義的符號便出現了。

於是在升級到0.14版之前，我則先將【newcj.cin】這個檔案，先行備份下來，然後在升級到0.14版後，

我則把先前備份的【newcj.cin】覆蓋到C:\Program Files (x86)\PIME\server\input_methods\newcj 之中

，然後我一樣是先到（輸入法碼表），先選非自由大新，確認完之後，再點入（輸入法碼表），再重

新選回自由大新，果然成功出現自定義的符號了。當時使用的系統版本是win7

然後在今天，我則打算如法泡製上述的方式，到我的筆電，而我的筆電是win10，而今天試了的結

果是一直都失敗，無法出現自定義的符號。然後今天回來，再使用win7系統的ＰＣ，發現昨天自定

義的按鍵方式，居然失效了，覺得滿困惑的，於是我剛剛又用了昨天一樣的方式再試試看，結果試

了幾次還是失敗，然後用著用著，也不知道是什麼原因又成功了，但現在又失效了～@@

雖然（設定輸入法模組）裡面的（簡易符號），也可以自定意想輸出的符號，不過得配合shift鍵才

可以輸出想要的符號，可能個人習慣上比較希望在打字過程之中，可以直接靠輸入的方式來自定義

按鍵，輸出想要的文字(句子)或符號、數字之類的～不知是否可以辦得到呢？

＊（支援 CIN 碼表中以符號字元所定義的編碼）這個選項我有打勾，記得是要將這選項打勾，在那
     個【newcj.cin】檔裡面所自定義的符號才會出現吧！？

問題可能有點長、複雜，勞煩各位朋友的協助，看是否有辦法能夠解決這個問題，感激不盡，謝謝！

**Comment by KenLuoTW** [comment]
```
我則把先前備份的【newcj.cin】覆蓋到C:\Program Files (x86)\PIME\server\input_methods\newcj 之中
```

這一段有問題喔,酷倉在 0.14 新版,碼表路徑已改為:

```
C:\Program Files (x86)\PIME\python\input_methods\checj\cin\
```

而下面這個路徑是舊版才有用到的資料夾,安裝程式解除時不會去移除它。
新版已完全沒有利用到這個資料夾,可以直接將它整個刪掉。

```
C:\Program Files (x86)\PIME\server\
```

**Comment by sirius95** [comment]
太感激你了，原來是路徑換了，我現把原先備份的自定義的cin檔，copy覆蓋到你

說的的路徑之中，果然馬上就出現我自定義的按鍵（文字符號數字）都出來了，

很謝謝你的幫忙，感激不盡！

**Comment by KenLuoTW** [comment]
以後我說不定會弄碼表擴展的功能,除了支援加入自訂的碼表,
我再看看能不能刪除碼表中不須要的資料,這樣以後改版就完全不用替換 cin。

因為酷倉的使用者設定檔存在下面這個路徑,這個不會隨改版就被替換或移除。

```
C:\Users\%用戶名稱%\PIME\checj\
```
