### ISSUE TITLE
有可能加入微軟新倉頡輸入法嗎？

### ISSUE THREAD

**Issue by freearcher** [EasyIME/forum#4]
PIME有可能是我目前用過最好的中文輸入法！

自從Windows 10升級後就不能用微軟新倉頡輸入法了，請問可以加入這個輸入法嗎？謝謝！

**Comment by InSb** [comment]
新倉頡輸入法與新酷音有異取同工之妙，若開發或許可以在新酷音模組基礎上開發，再結合對 cin 檔的支援。
不過個人感覺，實際上，新倉頡的優勢並不大，反倒偶爾有些惱人；實作新速成則更能顯出優勢。

**Comment by KenLuoTW** [comment]
新酷音模組很多功能利用新酷音的 chewing.dll 去達成,這個不是其它輸入法要用就可以拿來用的。
拿新酷音模組來開發,不會比拿現有的 CinBase 核心去擴展功能容易。

微軟新XX系列的特點就在於智能選字...等特點,這個要實現組字編輯區才能開發。
倉頡基本重碼字低,就算有了這些功能,也不會有多大的影響。

目前 CinBase 是有打算去擴展這些功能的,並將這些功能弄成可選項目,
所以未來不會有新倉頡、新速成模組的出現,有的只是現有模組功能的擴展。

只是近期應該把輕鬆輸入法弄完後,我就得先去處理別的事了,
故要有新的功能,得再等一段時間。

現有輸入法為何分開做,而不做成可讓用戶可自己選取 CIN 碼表的輸入法,
最大的原因是弄成通用的輸入法,就不能針對各輸入法的特性去各別再去做加強。
