### ISSUE TITLE
關於Pime0.14中大易模組的建議

### ISSUE THREAD

**Issue by Arthurmcarthur** [EasyIME/forum#7]
很高興看到Pime能推出大易的模組，但其中還存在著一個問題，希望能夠改進！
現在Pime大易是輸入中文字母之後按空格來檢視候選字，然後使用數字鍵來選字。但是由於大易輸入法佔用了數字鍵來輸入，這樣的方式會存在如下問題：例如，當我要輸入“知足”(編碼2vo 9）的時候，先輸入“2v0"，再按一次空格查看候選框，此時因為“知“字就在第一候選，我認為可以繼續打下去，於是我按下“9”，但是此時“9”鍵已經被選字的功能佔去，按“9”就不會有任何反應。我只能在輸入完“知”之後，按兩次空格，再按“9“，比較麻煩。
我提供兩種選字方案供參考： 
1.採用大易的傳統方式，仍然按空格檢視候選字，但把選字鍵改成Shift+從0開始的數字鍵。或者，把選字鍵改成 '[]-\ 和Shift+ '[]-\    。再或者，把一頁的候選字縮減至五個，選字鍵改成'[]-\      。
2.使用即時組字形式，空格鍵上屏，選字鍵同上一種方案。

**Comment by KenLuoTW** [comment]
會採用方案2,一會兒改出來會放在 #3 的連結裡(Test9)。

**Comment by Arthurmcarthur** [comment]
感謝 ！
