### ISSUE TITLE
PIME v0.15 發行前測試 

### ISSUE THREAD

**Issue by KenLuoTW** [EasyIME/forum#9]
這裡的測試版本是基於目前 code 所建立的測試版本。
目前的 code 可能會讓之前原本正常的功能,出現新 bug。
我已經將一些新 bug 排除,請大家幫忙看看還有什麼問題。

PIME 輸入法平台的新版安裝程式,已可以在沒有大變動時,直接安裝即可使用,
故往後測試模組都是直接使用新版安裝程式包裝。
https://drive.google.com/open?id=0B0FygkS7MtvXbWxCc2NzczRuSEE

組字編輯模式會在正式版本中停用,因為還未完成。
## 已知問題：
- 組字編輯模式尚未完成。(預計 0.15 不會開放此功能)
- 各種狀況下,按下 ESC 及 Backspace 鍵的行為有待確認是否正確。
## 
### Test01:
- 修正 cin-based 系列輸入法在目前 code 裡的 bug。
## 
## 
#### PIME 平台
- 修正在 Win7 下,無法辨識已安裝模組地區的問題。
## 
#### CIN 系列
- 修正當組字字根只有一個時,無法顯示候選清單視窗的問題。
## 
#### 組字編輯模式 (WIP)
- 完成組字編輯模式下的「向下鍵」選字功能。
## 
## 
#### PIME 平台
- 修正候選清單視窗無法完全關閉的問題。
- 訊息視窗現在可在無組字時,顯示在組字游標附近。
## 
## 
#### PIME 平台
- 修正因上一版本而產生出來的一些 bug。
## 
## 
#### PIME 平台
- 修正 https://github.com/EasyIME/forum/issues/9#issuecomment-249356319
##

**Comment by osfans** [comment]
支持。win7不可用的問題解決了嗎？好像把locale從zh-hans-cn改回zh-cn就好了

**Comment by KenLuoTW** [comment]
關鍵在 win7 的 
HKLM\SOFTWARE\Microsoft\CTF\TIP{35F67E9D-A54D-4177-9697-8B0AB71A9E04}\LanguageProfile

以新酷音模組來說,使用目前的 code 會將它底下的機碼寫入為 :

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\CTF\TIP\{35F67E9D-A54D-4177-9697-8B0AB71A9E04}\LanguageProfile\0x00000000\{F80736AA-28DB-423A-92C9-5540F501C939}
```

只要將它的上一層機碼改成中文繁體,所有的模組即可顯示出來:

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\CTF\TIP\{35F67E9D-A54D-4177-9697-8B0AB71A9E04}\LanguageProfile\0x00000404\{F80736AA-28DB-423A-92C9-5540F501C939}
```

如果把 locale 改回 zh-cn 在 win8 之後就會不正常。

**Comment by InSb** [comment]
看到 PIME 穩步發展，實在令人震奮。

不過小問題還是會有的：
- 使用酷倉等模組時，總會多出一條短竪線在螢幕上，只有關閉窗口或切換到其他非 cin-based 的 PIME 模組時，才會消失。
- 換用中州韻再馬上使用其他 PIME 模組，選單的字型仍保持為微軟雅黑。

明日繼續測。

**Comment by PCMan** [comment]
@KenLuoTW @osfans 
Win7 問題我剛修好了，用 ResolveLocaleName() 可轉換 RFC 4646 到 locale name
請測試最新的 git 版本 (需要 update libIME submodule)
Thanks!

**Comment by HPEACE** [comment]
打字後會留 | 有點困擾，這在0.14TEST時好像没有
![image](https://cloud.githubusercontent.com/assets/20449305/18407774/178f65ce-774d-11e6-847c-d46ab06db57c.png)
開愈多需要打字的視窗打愈多留愈多@@

**Comment by HPEACE** [comment]
補充
大易會，新酷音不會

**Comment by HPEACE** [comment]
候選字的排列好像調不過來，即使是改直向排它還是出現橫向排
![image](https://cloud.githubusercontent.com/assets/20449305/18408953/25e085c2-7770-11e6-82dc-eeda6b31b21c.png)

**Comment by HPEACE** [comment]
看來 0.15 的bug不少，再加1個
當在打字時偶而會發生「没有回應」，而這時也没辦法用滑鼠去點工作列已開啟的其他程式，整個Windows系統像是卡住狀態

**Comment by KenLuoTW** [comment]
@InSb 
1. 短竪線是候選清單視窗所留下的殘影,是 PIMETextService 的問題,新酷音模組同樣也有,只不過它預設不直接顯示候選清單,所以打字時並不會出現,要按向下鍵叫出候選清單才會。
2. Cin 系列模組目前都不會去設定顯示的字型,因為目前要顯示所有罕字,只有系統預設的字型。  
目前新酷音模組也未去設定顯示的字型,所以到時看新酷音要不要,我再來決定要怎麼做。

@HPEACE 
1. 留 |問題同上1。
2. 並沒發現不會套用設定的問題。
3. 大易我不會打,所以我無法去找出偶而會發生的問題。  
有問題也應該不會是偶而發生,而是有其規律可尋。

我覺得你可能是沒有安裝好,才會洐生出一些新問題,請確實利用安裝程式重新安裝。

**Comment by HPEACE** [comment]
@KenLuoTW  如你說的也許是安裝時產生的問題，所以就索性把它移除再重新安裝，目前僅剩 | 這個問題了

**Comment by s793016** [comment]
系統環境：
win10 x64
已將舊有版本移除並重開機，再安裝測試版。

目前問題：
1.rime 中州韻目前還是安裝在簡體中文語系下，這導致它不會直接出現在輸入法選單內，一定要我手動新增簡體中文語系後，它才會出現。
2.pime 內其它輸入法我選了 英數 / emoji ，然後安裝完後我無法再開啟 pime 設定選單，如果要加其它輸入法「只能移除重開機後，再安裝一次 pime」。

手動匯入附檔機碼把 rime 註冊在繁中語系下，可以直接在繁中選到 rime 輸入法。
[prime-0404.zip](https://github.com/EasyIME/forum/files/471441/prime-0404.zip)

**Comment by InSb** [comment]
Cin-based 系列模組，即使已選擇「直接顯示候選字清單 」，輸入只有一碼的文字時並不會有候選字清單。由於只有一碼時也可能有其他候選（如倉頡的`戈`、`中`等），所以偶爾令人困擾。

**Comment by KenLuoTW** [comment]
@InSb 已經修正於 TEST02。

@s793016 
1. 這應該是 PIME 或安裝程式所要處理的問題,不是模組的問題。
2. 英數 及 emoji 本來就沒有設定功能,所以無法開啟設定選單。
現階段要安裝模組必須由安裝程式去處理,或手動自己加入,設定功能內也沒有新增/移除輸入法旳功能。

**Comment by jojo62tw** [comment]
win7  x64  >> 語言列 >> 設定  >>  文字服務與輸入語言

當呈列各輸入法，點選「內容」，沒有任何反應，無法變更單一輸入法相關設定。

＝＝
語言列 >> 切換為  PIME 任一輸入法  >> 設定    (  可正常進入設定  )

語言列 >> 切換為  系統原有輸入法  >> 設定    (  無法進入設定  )

**Comment by KenLuoTW** [comment]
Test04 已更新,重新修正了候選清單在 0.15 版不會關閉的問題,不過這次是由 PIME 平台這邊修正。
新酷音及 CIN 系列模組的畫面殘留「短竪線」問題,也在此版本一併修正了。
切到中州韻再馬上使用其他 PIME 模組,目前除了新酷音,CIN系列應會換回細明體了。

目前工作地方的電腦很爛,致始我完全不想用來修改輸入法目前的問題,
再加上休息時間,可能會被其它的事情拖住,所以目前更新進度很慢。
我過陣子會去看看有沒有便宜效能又夠的中古電腦,拿來替換現在工作地方的電腦,
到時才會比較能夠快速的修正目前輸入法裡的問題。

**Comment by PCMan** [comment]
@KenLuoTW 太感謝了! 我今天放假難得有空，剛開始追這問題，還沒有查到就發現你修好了!
覺得我們是不是先來發個新版本？這次也隔了好久了。bug 總是沒有修完的一天啊... XD
大致上告一段落，確定不會弄壞系統，應該就可以發了。

**Comment by KenLuoTW** [comment]
@PCMan 目前應該是沒有問題了,可以暫時告一段落了。
之前發現的一些問題,好像也在修正了這個問題後,而自動消失了。
我也用了好幾天有問題的版本,畫面到處都是「候選清單」殘留的短竪線...

**Comment by PCMan** [comment]
那我來 build 一個新版本釋出了? @KenLuoTW 應該覺得可以吧? :)

**Comment by InSb** [comment]
真是辛苦了。
不過即使「預設隱藏提示訊息」關閉，在某些窗口下（如`notepad`）使用萬用字元出字時還是不會出取碼提示。

另，有時（如 Firefox 中）在打字後切換英數或中文模式後，上下左右鍵不能移動光標。

**Comment by KenLuoTW** [comment]
@InSb 已更新TEST05,麻煩幫忙看看 TEST05 有沒有修正這兩個問題。
須要重新開機以完成安裝,因為現在改得都是 PIME 平台的部份。

**Comment by InSb** [comment]
@KenLuoTW 已試用，暫沒發現問題。
提示訊息的停留時間似乎比以前要長，不過還好。

**Comment by KenLuoTW** [comment]
@InSb 以後會將提示時間改成自訂,顯示久一點主要是為了反應較慢的人(例如我),
怕還沒看清楚提示就消失了。另外只要隨便再輸入一個按鍵,提示也會自動消失。
